force-app/main/default/objects/Artifact__c/Artifact__c.object-meta.xml
<CustomObject>
    <label>Artifact</label>
    <nameField>
        <label>Artifact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artifacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Artifact__c/fields/Artifact_Factory__c.field-meta.xml
<CustomField>
    <fullName>Artifact_Factory__c</fullName>
    <label>Artifact Factory</label>
    <referenceTo>Artifact_Factory__c</referenceTo>
    <relationshipLabel>Artifacts</relationshipLabel>
    <relationshipName>Artifacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Artifact__c/fields/With__c.field-meta.xml
<CustomField>
    <fullName>With__c</fullName>
    <label>With</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Artifact_Factory__c/Artifact_Factory__c.object-meta.xml
<CustomObject>
    <label>Artifact Factory</label>
    <nameField>
        <label>Artifact Factory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artifact Factories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artifact_Version__c/Artifact_Version__c.object-meta.xml
<CustomObject>
    <label>Artifact Version</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Artifact Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Artifact Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Artifact_Version__c/fields/Artifact__c.field-meta.xml
<CustomField>
    <fullName>Artifact__c</fullName>
    <label>Artifact</label>
    <referenceTo>Artifact__c</referenceTo>
    <relationshipLabel>Artifact Versions</relationshipLabel>
    <relationshipName>Artifact_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ArtifactController.cls
/**
* @author luisfgarciar@gmail.com
* @date 2020
*
* @description Class to handle the Artifacts.
*/
public class ArtifactController {
    
    /**
    * @description Get the artifacts by factory ID.
    * returns a List of Artifacts.
    */
    @AuraEnabled
    Public static List<ArtifactSet> getArtifacts(string factoryId){ 
        List<ArtifactSet> resultList = new List<ArtifactSet>();
        
        List<Artifact__c> artifactList = [SELECT ID, NAME, Height__c, With__c, 
                                          (SELECT Version__c FROM Artifact_Versions__r) 
                                          FROM Artifact__c 
                                          WHERE Artifact_Factory__c = :factoryId];
        
        if(artifactList.size() >0) {
            for (Artifact__c artifact: artifactList) {
                ArtifactSet artifactResul = new ArtifactSet();
                artifactResul.name  =   artifact.Name;
                artifactResul.with  =   Integer.valueOf(artifact.With__c);
                artifactResul.height  =   Integer.valueOf(artifact.Height__c);
                artifactResul.versionsCount  =   artifact.Artifact_Versions__r.size();
                resultList.add(artifactResul);
            }
        }
        
        return resultList;
    }
}