force-app/main/default/objects/Artifact__c/Artifact__c.object-meta.xml
<CustomObject>
    <label>Artifact</label>
    <nameField>
        <label>Artifact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artifacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Artifact__c/fields/Artifact_Factory__c.field-meta.xml
<CustomField>
    <fullName>Artifact_Factory__c</fullName>
    <label>Artifact Factory</label>
    <referenceTo>Artifact_Factory__c</referenceTo>
    <relationshipLabel>Artifacts</relationshipLabel>
    <relationshipName>Artifacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Artifact__c/fields/With__c.field-meta.xml
<CustomField>
    <fullName>With__c</fullName>
    <label>With</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Artifact_Factory__c/Artifact_Factory__c.object-meta.xml
<CustomObject>
    <label>Artifact Factory</label>
    <nameField>
        <label>Artifact Factory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artifact Factories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artifact_Version__c/Artifact_Version__c.object-meta.xml
<CustomObject>
    <label>Artifact Version</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Artifact Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Artifact Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Artifact_Version__c/fields/Artifact__c.field-meta.xml
<CustomField>
    <fullName>Artifact__c</fullName>
    <label>Artifact</label>
    <referenceTo>Artifact__c</referenceTo>
    <relationshipLabel>Artifact Versions</relationshipLabel>
    <relationshipName>Artifact_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestArtifactController.cls
@isTest
public class TestArtifactController {
    
    static final String FACTORY_NAME='Factory ABC';
    static final String ARTIFACT_NAME='Artifact XYZ';
    static final Integer ARTIFACT_WITH=10;
    static final Integer ARTIFACT_HEIGHT=22;
    static final Integer NUMBER_OF_VERSIONS=3;
    
    @testSetup static void setup() {
        // Create Factory
        Artifact_Factory__c factory = new Artifact_Factory__c(Name = FACTORY_NAME);
        insert factory;  
        
        // Create Artifact
        Artifact__c artifact = new Artifact__c(Name = ARTIFACT_NAME, With__c=ARTIFACT_WITH, 
                                               Height__c=ARTIFACT_HEIGHT, Artifact_Factory__c=factory.Id );
        insert artifact;
        
        // Create Versions
        List<Artifact_Version__c> versionList = new List<Artifact_Version__c>();
        
        for(Integer i=1;i<=NUMBER_OF_VERSIONS;i++) {
            versionList.add(new Artifact_Version__c(Artifact__c=artifact.Id, Version__c=i));
        }
        insert versionList;
        
    }
    
    @isTest static void testGetArtifacts() {
        // Retrive the Factory.
        Artifact_Factory__c factory = [SELECT Id FROM Artifact_Factory__c WHERE Name = :FACTORY_NAME LIMIT 1];
        
        // Perform test
        Test.startTest();
        List<ArtifactSet> resultList = ArtifactController.getArtifacts(factory.Id);
        Test.stopTest();
        
        ArtifactSet result = resultList.get(0);
        
        // Verify 
        system.assertEquals( 1, resultList.size());
        system.assertEquals( ARTIFACT_NAME, result.name);
        system.assertEquals( ARTIFACT_WITH, result.with);
        system.assertEquals( ARTIFACT_HEIGHT, result.height);
        system.assertEquals( NUMBER_OF_VERSIONS, result.versionsCount);
    }
}